### PR TITLE
Removed interceptor.

### PR DESCRIPTION
**Pull request by kikoseijo**
Had to remove the interceptor, as its intercepting own calls on project.
Also, im not kind with migrations, but was a warning with 
```
[Element Migrating][ElTable][Event]: expand is renamed to expand-change
```

Not sure if you using 2 for double compatibility.
I just wanted to warn about the interceptor.

Reason I'm playing with this its because after update row click stop working, and its driving me crazy.
Cant find reason for not being working since update.

### CODE REVIEW

**Comment by kikoseijo** [comment]
Found the issue, seems `@row-click="rowClickHandler"` does not work, should be `v-on:row-click="rowClickHandler"` for the event to get captured.

**Comment by zollero** [comment]
@kikoseijo Yep, Element UI v2.x had renamed expand to expand-change, and I leave the `@expand`  to be compatible with Ele v1.x. Will be removed in the future.

And, `@row-click` works in my dev environment with Vue v2.5.9 and Ele v2.0.7.

And, the latest version of `el-search-table-pagination` is v0.4.14, if your `el-search-table-pagination` is not the latest version, please update it.

**Comment by kikoseijo** [comment]
Excellent tips, 
Probably something to do with my compliers, I have a sort of a disorder using async modules requires.

anyway, thanks for the response. you are so kind.

**Comment by kikoseijo** [comment]
Sorry forgot to say, 

your interceptor should return a promise and not an error.
Its intercepting all application requests, 

Your code has an interceptor:

screen shot 2017-12-08 at 04 01 36

And this is what happen if `status.code !== 200` and there is no `data`

screen shot 2017-12-08 at 04 04 42

**Comment by zollero** [comment]
@kikoseijo So glad to receive this. I will change it.

**Comment by zollero** [comment]
@kikoseijo I have change the interceptor. And release v0.4.15, [See detail](https://github.com/zollero/el-search-table-pagination/releases/tag/v0.4.15).

**Comment by kikoseijo** [comment]
There is also an issue, pagination stopped working.
after debugging I found that safari not able to match brackets annotations

```
if (response[totalField] && totalField && totalField.indexOf('.') !== -1) {
```

I had to remove `response[totalField] &&` because `response[totalField]` will always be null.

😱😱😱😱😱😱

**Comment by zollero** [comment]
@kikoseijo ok, I just remove it. 😂

**Comment by kikoseijo** [comment]
@zollero , what about rendering html without creating a new slot?

Im finding myself creating slots in the file I use as a template for all the models.

I think it should be easy.

**Comment by zollero** [comment]
@kikoseijo You mean this slot ?
image

**Comment by kikoseijo** [comment]
Also, this.$refs.crudTable.dataChangeHandler() with a Promisse I can show off errors to user without interceptors.

**Comment by zollero** [comment]
@kikoseijo PR please.

**Comment by kikoseijo** [comment]
Yes,

Could you explain what was your idea having implemented the interceptors?
i can make that also work, but dont understand the purpose of the interceptors in your case.

**Pull request closed without merging**
